# locale = 'en-us'

title = 'The Douglas Lab'

enableRobotsTXT = true

disableKinds = ["taxonomy", "term"] # turn off taxonomy terms so template doesnt look for them.

[permalinks.page]
"pages" = "/:slugorcontentbasename/"


[outputs]
page = [ "html" ]
home = [ "html", "json", "rss", "imagessitemap" ]

[outputFormats.IMAGESSITEMAP]
MediaType = "application/xml"
BaseName = "imagessitemap"
isPlainText = false
isHTML = false
noUgly = true
permalinkable = false

[sitemap]
changefreq = "weekly"
priority = 0.8
filename = "sitemap.xml"


defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = false  # or true if you want /en/ prefix

[build]
  [build.buildStats]
    enable = true
  [[build.cachebusters]]
    source = 'assets/notwatching/hugo_stats\.json'
    target = 'css'
  [[build.cachebusters]]
    source = '(postcss|tailwind)\.config\.js'
    target = 'css'


# This markup config is necessary, and
# required by the layouts/shorcode/download.html
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# the following caches is used only by github for github pages
# remove if you change hosting
[caches]
  [caches.images]
    dir = ':cacheDir/images'

[module]
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    disableWatch = true
    source = 'hugo_stats.json'
    target = 'assets/notwatching/hugo_stats.json'

[languages.en]
  contentDir = 'content/english'
  label = 'en'
  weight = 10
  [[languages.en.menus.main]]
    identifier = 'research'
    name = 'Research'
    pageRef = '/'
    weight = 1
  [[languages.en.menus.main]]
    identifier = 'people'
    name = 'People'
    pageRef  = '/people/'
    weight = 10
  [[languages.en.menus.main]]
    identifier = 'publications'
    name = 'Publications'
    pageRef  = '/publications/'
    weight = 20
  [[languages.en.menus.main]]
    identifier = 'downloads'
    name = 'Downloads'
    pageRef = '/downloads/'
    weight = 30
  [[languages.en.menus.main]]
    identifier = 'contact'
    name = 'Contact'
    pageRef = '/contact/'
    weight = 40

[languages.es]
  contentDir = 'content/espanol'
  label = 'es'
  weight = 20
  [[languages.es.menus.main]]
    identifier = 'research'
    name = 'Investigación'
    pageRef = '/'
    weight = 1
  [[languages.es.menus.main]]
    identifier = 'people'
    name = 'Personas'
    pageRef = '/people/'
    weight = 10
  [[languages.es.menus.main]]
    identifier = 'publications'
    name = 'Publicaciones'
    pageRef = '/publications/'
    weight = 20
  [[languages.es.menus.main]]
    identifier = 'downloads'
    name = 'Descargas'
    pageRef = '/downloads/'
    weight = 30
  [[languages.es.menus.main]]
    identifier = 'contact'
    name = 'Contacto'
    pageRef = '/contact/'
    weight = 40

